plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\DELL\\Desktop\\Document\\Footowlsolution\\apps\\web\\apps\\web\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm --workspace media-web-app run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]